apps/controle_de_ponto/urls.py
from django.urls import path, include
from . import views

app_name = 'controle_de_ponto'

urlpatterns = [
    path('', views.tela_inicial, name="tela_inicial"),
    path('cadastro_entrada/', views.cadastro_entrada, name="cadastro_entrada"),
    path('cadastro_saida/', views.cadastro_saida, name="cadastro_saida"),
    path('listar_registros/', views.listar_registros.as_view(), name="listar_registros"),
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from controle_de_ponto.api.viewsets import RegisterViewSet 

router = routers.DefaultRouter()
router.register('controle_de_ponto', RegisterViewSet)

urlpatterns = [
    path('', include('controle_de_ponto.urls', namespace='controle_de_ponto')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
]

apps/controle_de_ponto/models.py
from django.db import models

# Create your models here.

class RegisterManager(models.Manager):
    def search(self, search):
        print(search)
        return self.get_queryset().filter(**search)

class Register(models.Model):

    TIPO = [
        ('EN','Entrada'),
        ('SA','Saída'),
    ]

    rfid = models.CharField(max_length=40)
    data = models.DateField(auto_now_add=False)
    horario_entrada = models.TimeField('Horário entrada', auto_now=False, auto_now_add=False, blank=True, null=True)
    horario_saida = models.TimeField('Horário saída', auto_now=False, auto_now_add=False, blank=True, null=True)
    servico = models.TextField(blank=True)

    objects = models.Manager()
    registros = RegisterManager()

apps/controle_de_ponto/forms.py
from django import forms
from .models import Register

class RegisterForm(forms.ModelForm):
	class Meta:
		model = Register
		fields = '__all__'
		

apps/controle_de_ponto/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from .models import Register
from django.views.generic import ListView


# Create your views here.
def tela_inicial(request):
    template_name = 'controle_de_ponto/tela_inicial.html'

    return render(request, template_name, {})

def cadastro_entrada(request):
    template_name = 'controle_de_ponto/cadastro_entrada.html'
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                registro = Register.objects.get(rfid=form.cleaned_data['rfid'], horario_saida=None)
                messages.error(request, 'O funcionário já iniciou o expediente!')
            except:
                form.save()
                messages.success(request, 'Entrada registrada com sucesso!')

            return redirect('controle_de_ponto:tela_inicial')
        else:
            print(form.errors)
            
    form = RegisterForm()

    context = {
        'form':form,
    }

    return render(request, template_name, context)


def cadastro_saida(request):
    template_name = 'controle_de_ponto/cadastro_saida.html'
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            try:
                registro = Register.objects.get(rfid=form.cleaned_data['rfid'], horario_saida=None)
                registro.horario_saida = form.cleaned_data['horario_saida']
                registro.servico = form.cleaned_data['servico']
                registro.save()
                messages.success(request, 'Saída cadastrada com sucesso!')
            except:
                messages.error(request, 'O funcionário não iniciou o expediente!')
            
            return redirect('controle_de_ponto:tela_inicial')
        else:
            print(form.errors)
            
    form = RegisterForm()

    context = {
        'form':form,
    }

    return render(request, template_name, context)


class listar_registros(ListView):
	model = Register
	paginate_by = 20
	page_kwarg = 'page'

	context_object_name = 'registros'
	template_name = 'controle_de_ponto/listar_registros.html'

	link_search = str()

	def get(self, request, *args, **kwargs):	
		rfid = self.request.GET.get('rfid')

		search = {}

		# filtros para pesquisa
		if rfid:
			search['rfid'] = rfid
			self.link_search += '&rfid=' + rfid
        
		if request.GET:
            
			self.queryset = self.model.registros.search(search)

        

		return super(listar_registros, self).get(self, request, *args, **kwargs)

	def get_context_data(self, *, object_list=None, **kwargs):
		return super(listar_registros, self).get_context_data(
			count=self.model.objects.all().count(),
			link_search=self.link_search,
		)
	

    

templates/controle_de_ponto/cadastro_entrada.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Registrar início</title>

  <link rel = "icon" href = ""/>
  <!-- Custom fonts for this template-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-12">
                {% include 'partials/messages.html' %}
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h1 text-gray-900 m-4">REGISTRAR PONTO</h1>
                    <h3 class="h3 text-gray-900 m-4">(Entrada)</h3>
                  </div>
                  <form method="POST" action="{% url 'controle_de_ponto:cadastro_entrada' %}">
                    
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">TAG: </label>
                        {{ form.rfid | add_class:"form-control" }}
                    </div>

                    <div class="form-group">
                        <label for="">Data: </label>
                        {{ form.data | add_class:"form-control" }}
                    </div>

                    <div class="form-group">
                      <label for="">Horário: </label>
                      {{ form.horario_entrada | add_class:"form-control" | attr:"required" }}
                    </div>

                    <div class="form-group">
                      <button class="btn btn-primary btn-user btn-block" type="submit">REGISTRAR</button>
                    </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>

templates/controle_de_ponto/cadastro_saida.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Registrar saída</title>

  <link rel = "icon" href = ""/>
  <!-- Custom fonts for this template-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h1 text-gray-900 mb-4">REGISTRAR PONTO</h1>
                    <h3 class="h3 text-gray-900 m-4">(Saída)</h3>
                  </div>
                  <form method="POST" action="{% url 'controle_de_ponto:cadastro_saida' %}">
                    
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">TAG: </label>
                        {{ form.rfid | add_class:"form-control" }}
                    </div>

                    <div class="form-group">
                        <label for="">Data: </label>
                        {{ form.data | add_class:"form-control" }}
                    </div>

                    <div class="form-group">
                      <label for="">Horário saída: </label>
                      {{ form.horario_saida | add_class:"form-control" | attr:"required"}}
                    </div>

                    <div class="form-group">
                      <label for="">Serviço executado: </label>
                      {{ form.servico | add_class:"form-control" | attr:"required"}}
                    </div>

                    <div class="form-group">
                      <button class="btn btn-primary btn-user btn-block" type="submit">REGISTRAR</button>
                    </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>

templates/controle_de_ponto/listar_registros.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Listar registros</title>

  <link rel = "icon" href = ""/>
  <!-- Custom fonts for this template-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-12">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-12">
                {% include 'partials/messages.html' %}
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h1 text-gray-900 m-4">REGISTROS</h1>
                  </div>
                  <form class="table-responsive" id="table-list">
                    <div class="text-gray-800 mb-2 form-inline">
                      <div class="col-md-6 pl-0">
                        <h6>Exibindo <b>{{ page_obj.start_index }}-{{ page_obj.end_index }}</b> de <b>{{ count }}</b> ite{{ count|pluralize:"m,ns" }}.</h6>
                      </div>
                      {% if count > 20 %}
                        <div class="col-md">
                          <div class="form-group row float-md-right">
                            <label class="col-md col-form-label">Quantidade</label>
                            <select name="size" class="custom-select">
                              <option value="20" {% if request.GET.size == '20' %}selected{% endif %}>20</option>
                              <option value="25" {% if request.GET.size == '25' %}selected{% endif %}>25</option>
                              <option value="50" {% if request.GET.size == '50' %}selected{% endif %}>50</option>
                              <option value="100" {% if request.GET.size == '100' %}selected{% endif %}>100</option>
                            </select>
                          </div>
                        </div>
                      {% endif %}
                    </div>
                    <table class="table" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Tag</th>
                                <th>Data</th>
                                <th>Entrada</th>
                                <th>Saída</th> 
                                <th>Serviço</th> 
                                <th>&nbsp;</th>
                            </tr>
                            <tr>
                              <th>
                                <input type="text" class="form-control" name="rfid" value="{{ request.GET.nome }}" placeholder="Pesquise pela tag">
                              </th>
                              <th>&nbsp;</th>
                              <th>&nbsp;</th>
                              <th>&nbsp;</th>
                              <th>&nbsp;</th>
                              <th>&nbsp;</th>
                            </tr>
                        </thead>
                    
                        {% if registros %}
                        <tbody>
                            {% for registro in registros %}
                                <tr>
                                    <td>{{ registro.rfid }}</td>

                                    <td>{{ registro.data }}</td>
                                    <td>{{ registro.horario_entrada }}</td>
                                    <td>
                                        {% if registro.horario_saída %}
                                            {{ registro.horario_saída }}
                                        {% else %}
                                            <i class="text-danger">(Em serviço)</i>
                                        {% endif %}
                                    </td>
                                    <td>
                                      <button type="button" class="btn btn-sm btn-secondary my-auto" data-toggle="modal" data-target="#modal-{{registro.id}}">
                                        Descrição do serviço
                                      </button>
                                    </td>
                                </tr>
                                <div class="modal fade" id="modal-{{registro.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Descrição do Serviço</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                          {% if registro.servico %}
                                              {{ registro.servico }}
                                          {% else %}
                                              <i class="text-danger">Não consta</i>
                                          {% endif %}
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      
                                        </div>
                                    </div>
                                  </div>
                                </div>
                            {% endfor %}
                        </tbody>
                        {% endif %}
                    </table>               
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
  

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>

templates/controle_de_ponto/tela_inicial.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Controle de ponto</title>

  <link rel = "icon" href=""/>
  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-12">
                {% include 'partials/messages.html' %}
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h1 text-gray-900 mb-4">CONTROLE DE PONTO</h1>
                  </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                      </div>
                      <a href="{% url 'controle_de_ponto:cadastro_entrada' %}">
                        <button class="btn btn-primary btn-user btn-block mb-2" type="submit">REGISTRAR ENTRADA</button>
                      </a>
                      <a href="{% url 'controle_de_ponto:cadastro_saida' %}">
                        <button class="btn btn-primary btn-user btn-block mb-2" type="submit">REGISTRAR SAÍDA</button>
                      </a>
                      <a href="{% url 'controle_de_ponto:listar_registros' %}">
                        <button class="btn btn-primary btn-user btn-block mb-2" type="submit">LISTAR</button>
                      </a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>

templates/partials/messages.html
{% if messages %}

    {% for message in messages %}

        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        
    {% endfor %}

{% endif %}
    